---
title: "Hein_Conchola_2022"
author: "Zhiwei Xiao"
date: "2/21/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,message=FALSE,warning=FALSE,echo=FALSE}
library(Seurat)
library(tidyverse)
library(patchwork)
library(data.table)
library(hdf5r)
library(readxl)
library(leiden)
library(sctransform)
library(slingshot)
library(SingleCellExperiment)
library(RColorBrewer)
library(rgl)
library(grDevices)
library(destiny)
library(plotly)
```

## Figure 1
```{r}
your_mount_point <- "/Volumes/umms-spencejr/"
sample_lists <- c("304-1")
sample_species <- "human"
qc_max_mito <- ifelse(sample_species == "human", 10, 5)

general_cell_type_list <- c("EPCAM", "KRT18", "KRT8", "CLDN6", "VIM", "POSTN", "DCN", "TCF21", "COL1A2", "COL3A1", "TAGLN", "ACTA2", "PDGFRB", "PTPRC", "CD37", "CORO1A", "LCP1", "CD53", "LAPTM5", "CDH5", "CLDN5", "ESAM", "KDR", "FLT1", "S100B", "ELAVL4", "TUBB2B", "STMN2", "ASCL1", "NNAT", "GRP", "MPZ", "MKI67", "TOP2A", "CDK1", "TYMS", "H2AFZ", "STMN1", "LGR5")

cell_lineage_list <- c("NKX2-1", "CDX2", "PAX8", "PDX1", "HHEX", "NES", "SOX1", "PAX6", "SOX17", "FOXA2", "SOX2", "HES1", "IRX1")

bud_tip_list <- c("SOX9", "CPM", "FGF20", "SOX11", "HMGB2", "NPC2", "LGR5", "ETV5", "ETV4", "RNF43", "ZNRF3", "TESC")

lung_epithelium_list <- c("SOX9", "SFTPC", "NPC2", "TESC", "CA2", "ETV5", "SOX2", "TP63", "KRT5", "KRT15", "IL33", "FOXL1", "FOXJ1", "CHGA", "SYN1", "MUC5AC", "MUC5B", "FOXA3", "SCGB1A1", "BPIFA1", "SCGB3A2", "CFTR", "SFTPB", "HOPX", "PDPN", "AQP5", "AGER", "ABCA3", "ASCL1")

cell_lineage_list_updated <-  c("POU5F1", "SOX1", "SOX17", "FOXA2", "TBXT", "SOX2", "HHEX", "CDX2", "NKX2-1", "PAX8", "IRX1", "TP63", "PDX1", "ALB")

spheroid_list_supplement <- c("EPCAM", "KRT18", "KRT8", "CLDN6", "POSTN", "COL1A1", "COL3A1", "TAGLN", "ACTA2", "PDGFRB", "CDH5", "CLDN5", "ESAM", "KDR", "FLT1", "S100B", "ELAVL4", "STMN2", "TUBB2B", "ASCL1", "NNAT", "GRP", "MPZ", "MKI67", "TOP2A", "CDK1")

spheroid_list_main <- c("SOX2", "POU5F1", "SOX1", "TBXT", "SOX17", "FOXA2", "CDX2", "HHEX", "NKX2-1", "TP63", "PDX1", "PAX8", "ALB")

spheroid_list_main2 <- c("SOX2", "POU5F1", "SOX1", "TBXT", "SOX17", "FOXA2", "CDX2", "HHEX", "NKX2-1", "TP63", "PDX1", "PAX8", "ALB", "FOXP1", "FOXP2", "SOX9")

spheroid_list_main3 <- unique(c("SOX2", "POU5F1", "SOX1", "TBXT", "SOX17", "FOXA2", "FOXA3", "CDX2", "HOXC5", "HOXC6", "HOXB6", "HOXB8", "HOXC9", "HOXB9", "HHEX", "NKX2-1", "HOXA3", "HOXB4", "TP63", "TBX1", "PDX1", "PAX8", "PAX9", "HOXB1", "ALB", "ONECUT1", "FOXP1", "FOXP2", "FOXP4", "GATA6", "FOXA3", "CEBPA", "SOX9"))


spheroid_list_main4 <- c("SOX2", "POU5F1", "SOX1", "TBXT", "SOX17", "FOXA2", "FOXP1", "FOXP2", "FOXP4", "GATA6", "CEBPA", "HHEX", "NKX2-1", "FOXA3", "CDX2", "TP63", "TBX1", "PDX1", "PAX8", "ALB")

spheroid_list_main5 <- c("SOX2", "POU5F1", "NANOG", "SOX1", "TBXT", "SOX17", "FOXA2", "FOXP1", "FOXP2", "FOXP4", "GATA6", "CEBPA", "HHEX", "NKX2-1", "FOXA3", "CDX2", "HAND1", "TP63", "TBX1", "PDX1", "PAX8", "ALB")

spheroid_list_main6 <- c("SOX2", "POU5F1", "NANOG", "SOX1", "TBXT", "SOX17", "FOXA2", "NANOS3", "TFAP2C", "FOXP1", "FOXP2", "FOXP4", "GATA6", "CEBPA", "HHEX", "NKX2-1", "FOXA3", "CDX2", "HAND1", "GATA3", "KRT7", "ISL1", "WNT6", "GABRP", "BMP4", "TFAP2A", "TP63", "TBX1", "PDX1", "PAX8", "ALB")


spheroid_list_main7 <- unique(c("SOX2", "POU5F1", "NANOG", "SOX1", "TBXT", "SOX17", "FOXA2", "NANOS3", "TFAP2C", "FOXP1", "FOXP2", "FOXP4", "GATA6", "CEBPA", "HHEX", "NKX2-1", "FOXA3", "CDX2", "HAND1", "GATA3", "KRT7", "ISL1", "WNT6", "GABRP", "BMP4", "TFAP2A", "FOXF1", "LEF1", "TP63", "TBX1", "PDX1", "PAX8", "ALB"))

spheroid_list_main_final1 <- unique(c("SOX2", "POU5F1", "NANOG", "SOX1", "TBXT", "SOX17", "FOXA2", "FOXP1", "FOXP2", "FOXP4", "GATA6", "CEBPA", "HHEX", "NKX2-1", "FOXA3", "CDX2", "TP63", "TBX1", "PDX1", "PAX8", "ALB"))

spheroid_list_supplement_final1 <- unique(c("EPCAM", "KRT18", "KRT8", "CLDN6", "POSTN", "COL1A1", "COL3A1", "TAGLN", "ACTA2", "PDGFRB", "CDH5", "CLDN5", "ESAM", "KDR", "FLT1", "S100B", "ELAVL4", "STMN2", "TUBB2B", "ASCL1", "NNAT", "GRP", "MPZ", "KI67", "TOP2A", "CDK1", "NANOS3", "TFAP2C", "HAND1", "GATA3", "KRT7", "ISL1", "WNT6", "GABRP", "BMP4", "TFAP2A", "FOXF1", "LEF1"))

spheroid_list_supplement_final2 <- unique(c("EPCAM", "KRT18", "KRT8", "CLDN6", "POSTN", "DCN", "COL1A2", "COL3A1", "CDH5", "CLDN5", "ESAM", "KDR", "S100B", "ELAVL4", "STMN2", "ASCL1", "MKI67", "TOP2A", "CDK1", "POU5F1", "NANOG", "TBXT", "NANOS3", "TFAP2C", "ISL1", "HAND1", "BMP4", "FOXF1", "LEF1")) 



metadata_table <- as.data.frame(read_xls(paste(your_mount_point,
                                "01_RNAseq_RAW_Data/single_cell_meta_data_table_excel.xls",
                                sep = ""), col_names = FALSE))

colnames(metadata_table)[1:12] <- c("sample_ID","sample_path","age","tissue","gel","media","sex",
                                   "sampleName","dataset","EGF_treatment","NRG1_treatment","EREG_treatment")

metadata_table <- as.data.frame(lapply(metadata_table, function(x) gsub(".*:", "", x)))


sample_paths <- "/Volumes/mcomm-spencelab/01_RNAseq_RAW_Data/NovaA-304/Client/1789-RC/NovaA-304/Sample_1789-RC-1_GCGGGTAA-CTTAGTGC/outs/filtered_feature_bc_matrix.h5"

seurat_source <- Seurat::Read10X_h5(filename = sample_paths, use.names = TRUE, unique.features = TRUE)

final_seurat_object <- Seurat::CreateSeuratObject(counts = seurat_source,
                                                                   project = sample_lists)

final_seurat_object[["percent.mt"]] <- ifelse(sample_species == "human",
                                                  PercentageFeatureSet(final_seurat_object, pattern = "^MT-"),
                                                  PercentageFeatureSet(final_seurat_object, pattern = "^mt-"))

qc_min_genes= 500
qc_min_counts = 500
qc_max_genes = 8000
qc_max_counts = 50000


final_seurat_object <- subset(final_seurat_object, subset = nFeature_RNA >= qc_min_genes &
                                nFeature_RNA <= qc_max_genes & percent.mt <= qc_max_mito &
                                nCount_RNA >= qc_min_counts & nCount_RNA <= qc_max_counts)

set.seed(888)

final_seurat_object <- SCTransform(final_seurat_object,
                                        vars.to.regress = "percent.mt", verbose = FALSE)

final_seurat_object <- RunPCA(final_seurat_object, verbose = FALSE)

final_seurat_object <- RunUMAP(final_seurat_object, dims = 1:20)
final_seurat_object <- FindNeighbors(final_seurat_object, dims = 1:20)
final_seurat_object <- FindClusters(final_seurat_object, resolution = 0.2, algorithm = 4)

DefaultAssay(final_seurat_object) <- "RNA"
final_seurat_object <- NormalizeData(final_seurat_object, 
                                            normalization.method = "LogNormalize", scale.factor =10000)


test_dataset <- as.data.frame(final_seurat_object[["umap"]]@cell.embeddings)

final_seurat_object <- final_seurat_object[,!colnames(final_seurat_object) %in% rownames(test_dataset[test_dataset$UMAP_1>20,])]

set.seed(888)

final_seurat_object <- SCTransform(final_seurat_object,
                                        vars.to.regress = "percent.mt", verbose = FALSE)

final_seurat_object <- RunPCA(final_seurat_object, verbose = FALSE)

final_seurat_object <- RunUMAP(final_seurat_object, dims = 1:20)
final_seurat_object <- FindNeighbors(final_seurat_object, dims = 1:20)
final_seurat_object <- FindClusters(final_seurat_object, resolution = 0.2, algorithm = 4)

DefaultAssay(final_seurat_object) <- "RNA"
final_seurat_object <- NormalizeData(final_seurat_object, 
                                            normalization.method = "LogNormalize", scale.factor =10000)

Dotplot_Zhiwei_Version <- function(seurat_object, gene_list) {
  
DotPlot(seurat_object, features = gene_list) + RotatedAxis() +
   scale_colour_gradientn(colors =                                                                                  c("lightgrey","#ffffd9","#edf8b1","#c7e9b4","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#253494","#081d58"))+
  guides(size=guide_legend(title = "Percent Expressed",override.aes=list(shape=21, colour="black", fill="white"))) +
  labs(y="Cluster", x= NULL) +
  guides(color = guide_colourbar(title = "Average Expression", ticks = TRUE, frame.colour = "black")) +
  theme(axis.line.x.bottom = element_blank(),axis.line.y.left = element_blank())+ 
  theme(panel.border=element_rect(colour="black",fill=NA,size=0.8))
  
}



## plotting, using spheroid_list_supplement_final2 gene list as an example

Dotplot_Zhiwei_Version(final_seurat_object,spheroid_list_supplement_final2)

FeaturePlot(final_seurat_object, features = spheroid_list_supplement_final2,raster = FALSE,
            slot = "data",pt.size = 0.6,order = TRUE) & RotatedAxis() & scale_colour_gradientn(colors =                                                                                  c("lightgrey","#ffffd9","#edf8b1","#c7e9b4","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#253494","#081d58")) &   xlab("UMAP1") & ylab("UMAP2")

```



## Figure 2
```{r,message=FALSE,warning=FALSE}
your_mount_point <- "/Volumes/umms-spencejr/"
sample_lists <- c("4511-1","4511-2","4511-3","4511-4","4511-5")
sample_species <- "human"
qc_max_mito <- ifelse(sample_species == "human", 10, 5)


general_cell_type_list <- c("EPCAM", "KRT18", "KRT8", "CLDN6", "VIM", "POSTN", "DCN", "TCF21", "COL1A2", "COL3A1", "TAGLN", "ACTA2", "PDGFRB", "PTPRC", "CD37", "CORO1A", "LCP1", "CD53", "LAPTM5", "CDH5", "CLDN5", "ESAM", "KDR", "FLT1", "S100B", "ELAVL4", "TUBB2B", "STMN2", "ASCL1", "NNAT", "GRP", "MPZ", "MKI67", "TOP2A", "CDK1", "TYMS", "H2AFZ", "STMN1", "LGR5")

cell_lineage_list <- c("NKX2-1", "CDX2", "PAX8", "PDX1", "HHEX", "NES", "SOX1", "PAX6", "SOX17", "FOXA2", "SOX2", "HES1", "IRX1")

bud_tip_list <- c("SOX9", "CPM", "FGF20", "SOX11", "HMGB2", "NPC2", "LGR5", "ETV5", "ETV4", "RNF43", "ZNRF3", "TESC")

lung_epithelium_list <- c("SOX9", "SFTPC", "NPC2", "TESC", "CA2", "ETV5", "SOX2", "TP63", "KRT5", "KRT15", "IL33", "FOXL1", "FOXJ1", "CHGA", "SYN1", "MUC5AC", "MUC5B", "FOXA3", "SCGB1A1", "BPIFA1", "SCGB3A2", "CFTR", "SFTPB", "HOPX", "PDPN", "AQP5", "AGER", "ABCA3", "ASCL1")


LPO_list_supplement <- c("EPCAM", "KRT18", "KRT8", "CLDN6", "POSTN", "DCN", "COL1A2", "COL3A1", "CDH5", "CLDN5", "ESAM", "KDR", "S100B", "ELAVL4", "STMN2", "ASCL1", "MKI67", "TOP2A", "CDK1")


Charlie_list <- c("CDX2","LGR5","OLFM4","DEFA5","MUC2","CHGA","DPP4","SI","BEST4","NKX2-1")


heatmap_list <- c("FABP1", "RBP2", "GSTA1", "PHGR1", "MTTP", "AMN", "ANPEP", "PRAP1", "NOSTRIN", "SLC51A", "SLC51B", "MEP1A", "ACSL5", "CDX1", "CDX2", "KRT17", "IGF2", "ISL1", "LUZP2", "TNNT3", "ARL4C", "CD48", "SEMA3D", "GATA3", "NECTIN4", "HOXD13", "UPK2", "HOXD11", "CPA6", "PDPN", "THBS1", "TPPP3", "CPM", "TESC", "NKX2-1", "SFTA3", "TGFB2", "FGF20", "WNT7B", "ETV5", "FOXA2", "LIFR", "SP5", "FZD2", "SERPINF1", "COL3A1", "COL1A2", "COL1A1", "VIM", "COL6A2", "LUM", "COL6A3", "COL6A1", "TWIST1", "WNT5A", "CDH11", "MMP11", "PTCH1", "COL5A2", "DCN", "CHGA", "NEUROD1", "STMN2", "FEV", "PCSK1", "OR51E1", "SCG2", "PAX4", "ASCL1", "SCG3", "CLPS", "KCNH6", "CHGB", "NKX2-2", "KIF19", "FCGBP", "CLCA1", "MUC2", "DLL1", "BCAS1", "SPDEF", "AGXT", "LRRC26", "CAPN9", "GUCA2B", "RAB26", "FRZB", "ANO1", "DLL4", "WNT4", "CA7", "SPIB", "OTOP2", "BEST4", "AIF1", "DMBT1", "GUCA2B", "LGALS9", "CTSE", "CA4", "CARD16", "REN", "NEURL1", "CA3", "ADCY5")


metadata_table <- as.data.frame(read_xls(paste(your_mount_point,
                                '01_RNAseq_RAW_Data/single_cell_meta_data_table_excel.xls',
                                sep = ''), col_names = FALSE))

colnames(metadata_table)[1:12] <- c("sample_ID","sample_path","age","tissue","gel","media","sex",
                                   "sampleName","dataset","EGF_treatment","NRG1_treatment","EREG_treatment")

metadata_table <- as.data.frame(lapply(metadata_table, function(x) gsub(".*:", "", x)))

sample_paths <- paste(your_mount_point,subset(metadata_table, sample_ID %in% sample_lists)[,2],sep='')

seurat_source_list <- lapply(sample_paths, function(x) Seurat::Read10X_h5(filename = x, use.names = TRUE, unique.features = TRUE))


names(seurat_source_list) <- sample_lists


seurat_object_list <- lapply(seq_along(seurat_source_list),
                            function(i) Seurat::CreateSeuratObject(counts = seurat_source_list[[i]],
                                                                   project = names(seurat_source_list)[i]))
rm(seurat_source_list)

# create the final seurat object that contains all the samples
final_seurat_object <- merge(seurat_object_list[[1]], 
                            y = seurat_object_list[2:length(seurat_object_list)])

final_seurat_object[["percent.mt"]] <- ifelse(sample_species == "human",
                                                  PercentageFeatureSet(final_seurat_object, pattern = "^MT-"),
                                                  PercentageFeatureSet(final_seurat_object, pattern = "^mt-"))

qc_min_genes <- 500
qc_min_counts <- 500
qc_max_genes <- 7000
qc_max_counts <- 50000


final_seurat_object <- subset(final_seurat_object, subset = nFeature_RNA >= qc_min_genes &
                                nFeature_RNA <= qc_max_genes & percent.mt <= qc_max_mito &
                                nCount_RNA >= qc_min_counts & nCount_RNA <= qc_max_counts)
final_seurat_object <- SplitObject(final_seurat_object, split.by = "orig.ident")

set.seed(888)
for (i in 1:length(final_seurat_object)) {
    final_seurat_object[[i]] <- SCTransform(final_seurat_object[[i]], 
                                            verbose = FALSE, vars.to.regress = "percent.mt")
}

final_seurat_object_features <- SelectIntegrationFeatures(object.list = final_seurat_object, 
                                                          nfeatures = 3000)
final_seurat_object <- PrepSCTIntegration(object.list = final_seurat_object, 
                                          anchor.features = final_seurat_object_features)

final_seurat_object_anchors <- FindIntegrationAnchors(object.list = final_seurat_object, 
                                           normalization.method = "SCT", 
                                           anchor.features = final_seurat_object_features)

final_seurat_object_integrated <- IntegrateData(anchorset = final_seurat_object_anchors, 
                                     normalization.method = "SCT")

set.seed(888)
final_seurat_object_integrated <- RunPCA(final_seurat_object_integrated, verbose = FALSE)
final_seurat_object_integrated <- RunUMAP(final_seurat_object_integrated, dims = 1:30)
final_seurat_object_integrated <- FindNeighbors(final_seurat_object_integrated, dims = 1:30)
final_seurat_object_integrated <- FindClusters(final_seurat_object_integrated, resolution = 0.08, algorithm = 1)

DefaultAssay(final_seurat_object_integrated) <- "RNA"

final_seurat_object_integrated <- NormalizeData(final_seurat_object_integrated, 
                                            normalization.method = "LogNormalize", scale.factor =10000)

DimPlot(final_seurat_object_integrated, reduction = "umap", shuffle=TRUE, repel = TRUE,label = TRUE) +  labs(color = "Cluster") + xlab("UMAP1") + ylab("UMAP2") + labs(title = NULL)

DimPlot(final_seurat_object_integrated, reduction = "umap", group.by = 'orig.ident', shuffle=TRUE, repel = TRUE) +  labs(color = "Sample") + xlab("UMAP1") + ylab("UMAP2") + labs(title = NULL)

Dotplot_Zhiwei_Version(final_seurat_object_integrated,LPO_list_supplement)
```



## Figure 3
```{r}
your_mount_point <- "/Volumes/umms-spencejr/"
sample_lists <- c("5178-1","5178-2")
sample_species <- "human"
qc_max_mito <- ifelse(sample_species == "human", 10, 5)

metadata_table <- as.data.frame(read_xls(paste(your_mount_point,
                                '01_RNAseq_RAW_Data/single_cell_meta_data_table_excel.xls',
                                sep = ''), col_names = FALSE))

colnames(metadata_table)[1:12] <- c("sample_ID","sample_path","age","tissue","gel","media","sex",
                                   "sampleName","dataset","EGF_treatment","NRG1_treatment","EREG_treatment")

metadata_table <- as.data.frame(lapply(metadata_table, function(x) gsub(".*:", "", x)))

sample_paths <- paste(your_mount_point,subset(metadata_table, sample_ID %in% sample_lists)[,2],sep='')

seurat_source_list <- lapply(sample_paths, function(x) Seurat::Read10X_h5(filename = x, use.names = TRUE, unique.features = TRUE))


names(seurat_source_list) <- sample_lists


seurat_object_list <- lapply(seq_along(seurat_source_list),
                            function(i) Seurat::CreateSeuratObject(counts = seurat_source_list[[i]],
                                                                   project = names(seurat_source_list)[i]))
rm(seurat_source_list)

final_seurat_object <- merge(seurat_object_list[[1]], 
                            y = seurat_object_list[2:length(seurat_object_list)])

final_seurat_object[["percent.mt"]] <- ifelse(sample_species == "human",
                                                  PercentageFeatureSet(final_seurat_object, pattern = "^MT-"),
                                                  PercentageFeatureSet(final_seurat_object, pattern = "^mt-"))

qc_min_genes <- 200
qc_min_counts <- 200
qc_max_genes <- 9500
qc_max_counts <- 50000


final_seurat_object <- subset(final_seurat_object, subset = nFeature_RNA >= qc_min_genes &
                                nFeature_RNA <= qc_max_genes & percent.mt <= qc_max_mito &
                                nCount_RNA >= qc_min_counts & nCount_RNA <= qc_max_counts)

final_seurat_object <- SplitObject(final_seurat_object, split.by = "orig.ident")

set.seed(888)
for (i in 1:length(final_seurat_object)) {
    final_seurat_object[[i]] <- SCTransform(final_seurat_object[[i]], 
                                            verbose = FALSE, vars.to.regress = "percent.mt")
}

final_seurat_object_features <- SelectIntegrationFeatures(object.list = final_seurat_object, 
                                                          nfeatures = 3000)
final_seurat_object <- PrepSCTIntegration(object.list = final_seurat_object, 
                                          anchor.features = final_seurat_object_features)

final_seurat_object_anchors <- FindIntegrationAnchors(object.list = final_seurat_object, 
                                           normalization.method = "SCT", 
                                           anchor.features = final_seurat_object_features)

final_seurat_object_integrated <- IntegrateData(anchorset = final_seurat_object_anchors, 
                                     normalization.method = "SCT")

set.seed(888)
final_seurat_object_integrated <- RunPCA(final_seurat_object_integrated, verbose = FALSE)
final_seurat_object_integrated <- RunUMAP(final_seurat_object_integrated, dims = 1:30)
final_seurat_object_integrated <- FindNeighbors(final_seurat_object_integrated, dims = 1:30)
final_seurat_object_integrated <- FindClusters(final_seurat_object_integrated, resolution = 0.2, algorithm = 4)
DefaultAssay(final_seurat_object_integrated) <- "RNA"
final_seurat_object_integrated <- NormalizeData(final_seurat_object_integrated, 
                                            normalization.method = "LogNormalize", scale.factor =10000)

Dotplot_Zhiwei_Version(final_seurat_object_integrated,LPO_list_supplement)
FeaturePlot(final_seurat_object_integrated, features = LPO_list_supplement,raster = FALSE,
            slot = "data",pt.size = 0.4,order=TRUE) & RotatedAxis() & scale_colour_gradientn(colors =                                                                                  c("lightgrey","#ffffd9","#edf8b1","#c7e9b4","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#253494","#081d58")) &   xlab("UMAP1") & ylab("UMAP2")
```




## Cell Scoring Figures
```{r,message=FALSE,warning=FALSE}
your_mount_point <- "/Volumes/umms-spencejr/"
sample_lists <- c("4511-1","4511-2","4511-3","4511-4","4511-5")
sample_species <- "human"
qc_max_mito <- ifelse(sample_species == "human", 10, 5)


metadata_table <- as.data.frame(read_xls(paste(your_mount_point,
                                '01_RNAseq_RAW_Data/single_cell_meta_data_table_excel.xls',
                                sep = ''), col_names = FALSE))

colnames(metadata_table)[1:12] <- c("sample_ID","sample_path","age","tissue","gel","media","sex",
                                   "sampleName","dataset","EGF_treatment","NRG1_treatment","EREG_treatment")

metadata_table <- as.data.frame(lapply(metadata_table, function(x) gsub(".*:", "", x)))

sample_paths <- paste(your_mount_point,subset(metadata_table, sample_ID %in% sample_lists)[,2],sep='')

seurat_source_list <- lapply(sample_paths, function(x) Seurat::Read10X_h5(filename = x, use.names = TRUE, unique.features = TRUE))


names(seurat_source_list) <- c("3-week LPOs (NKX2-1-extracted)","3-week LPOs (NKX2-1-extracted)",
                               "6-week LPOs (NKX2-1-extracted)","6-week LPOs (NKX2-1-extracted)",
                               "10-week LPOs (NKX2-1-extracted)")


seurat_object_list <- lapply(seq_along(seurat_source_list),
                            function(i) Seurat::CreateSeuratObject(counts = seurat_source_list[[i]],
                                                                   project = names(seurat_source_list)[i]))
rm(seurat_source_list)


final_seurat_object <- merge(seurat_object_list[[1]], 
                            y = seurat_object_list[2:length(seurat_object_list)])

rm(seurat_object_list)

ac1_to_ac5_NKX_positive_cells <- colnames(final_seurat_object[["RNA"]]@counts[,final_seurat_object[["RNA"]]@counts["NKX2-1",]!=0])

final_seurat_object <- final_seurat_object[,colnames(final_seurat_object) %in% ac1_to_ac5_NKX_positive_cells]

positive_reference_seurat_source <- Seurat::Read10X_h5(filename = "/Volumes/umms-spencejr/01_RAW_RNASEQ_AGC_SHARE/MiStorage Transfer/Run_2402/Sample_HT145-3F-redo/outs/filtered_gene_bc_matrices_h5.h5", use.names = TRUE, unique.features = TRUE)
positive_reference_seurat_object <- Seurat::CreateSeuratObject(counts = positive_reference_seurat_source,
                                                                   project = "Human Fetal Bud Tip Organoids")

final_seurat_object <- merge(final_seurat_object, 
                            y = c(positive_reference_seurat_object))

final_seurat_object[["percent.mt"]] <- ifelse(sample_species == "human",
                                                  PercentageFeatureSet(final_seurat_object, pattern = "^MT-"),
                                                  PercentageFeatureSet(final_seurat_object, pattern = "^mt-"))

qc_min_genes= 200
qc_min_counts = 200
qc_max_genes = 9500
qc_max_counts = 60000


final_seurat_object <- subset(final_seurat_object, subset = nFeature_RNA >= qc_min_genes &
                                nFeature_RNA <= qc_max_genes & percent.mt <= qc_max_mito &
                                nCount_RNA >= qc_min_counts & nCount_RNA <= qc_max_counts)


final_seurat_object_361014_integrated_bud_tip_cluster <- readRDS("/Users/zhiweixiao/Documents/Seurat_Objects/final_seurat_object_361014_integrated_bud_tip_cluster_updated.rds")

levels(final_seurat_object_361014_integrated_bud_tip_cluster@active.ident) <- rep("In vivo Bud Tip",2)
final_seurat_object_361014_integrated_bud_tip_cluster$orig.ident <- "In vivo Bud Tip"

final_seurat_object_361014_integrated_basal_cluster <-
  readRDS("/Users/zhiweixiao/Documents/Seurat_Objects/final_seurat_object_361014_integrated_basal_cluster_updated.rds")

levels(final_seurat_object_361014_integrated_basal_cluster@active.ident) <- rep("In vivo Basal Cell",2)
final_seurat_object_361014_integrated_basal_cluster$orig.ident <- "In vivo Basal Cell"


final_seurat_object_361014_integrated_neuroendocrine_cluster <- 
  readRDS("/Users/zhiweixiao/Documents/Seurat_Objects/final_seurat_object_361014_integrated_neuroendocrine_cluster.rds")

levels(final_seurat_object_361014_integrated_neuroendocrine_cluster@active.ident) <- rep("In vivo Neuroendocrine",2)
final_seurat_object_361014_integrated_neuroendocrine_cluster$orig.ident <- "In vivo Neuroendocrine"


ansley_renee_5178_1_object <- readRDS("/Users/zhiweixiao/Documents/Seurat_Objects/ansley_renee_5178-1_object.rds")
levels(ansley_renee_5178_1_object@active.ident) <- rep("iBTOs(10-week Sorted)",4)
ansley_renee_5178_1_object$orig.ident <- "iBTOs(10-week Sorted)"

ansley_renee_5178_2_object <- readRDS("/Users/zhiweixiao/Documents/Seurat_Objects/ansley_renee_5178-2_object.rds")
levels(ansley_renee_5178_2_object@active.ident) <- rep("iBTOs(4-week Sorted)",4)
ansley_renee_5178_2_object$orig.ident <- "iBTOs(4-week Sorted)"


final_seurat_object_integrated_4511_combined <- readRDS("/Users/zhiweixiao/Documents/Seurat_Objects/final_seurat_object_integrated_4511_combined.rds")
levels(final_seurat_object_integrated_4511_combined@active.ident) <- rep("3 - 10-week Whole LPOs",7)
final_seurat_object_integrated_4511_combined$orig.ident <- "3 - 10-week Whole LPOs"

final_seurat_object <- merge(final_seurat_object, 
                            y = c(final_seurat_object_361014_integrated_bud_tip_cluster,final_seurat_object_361014_integrated_basal_cluster,
                                  final_seurat_object_361014_integrated_neuroendocrine_cluster,
                                  ansley_renee_5178_1_object,
                                  ansley_renee_5178_2_object,
                                  final_seurat_object_integrated_4511_combined))

set.seed(888)
DefaultAssay(final_seurat_object) <- "RNA"
final_seurat_object <- NormalizeData(final_seurat_object, 
                                            normalization.method = "LogNormalize", scale.factor =10000)


bud_tip_cell_scoring_list <- list(readRDS("/Users/zhiweixiao/Documents/Seurat_Objects/bud_tip_cell_scoring_list.rds"))

basal_cell_scoring_list <- list(readRDS("/Users/zhiweixiao/Documents/Seurat_Objects/basal_cell_scoring_list.rds"))

neuroendocrine_cell_scoring_list <- list(readRDS("/Users/zhiweixiao/Documents/Seurat_Objects/neuroendocrine_cell_scoring_list.rds"))


set.seed(888)
final_seurat_object <-AddModuleScore(final_seurat_object, features = bud_tip_cell_scoring_list, 
                                     name = "bud tip cell scoring list", search = TRUE, assay = "RNA")

final_seurat_object <-AddModuleScore(final_seurat_object, features = basal_cell_scoring_list, 
                                     name = "basal cell scoring list", search = TRUE, assay = "RNA")

final_seurat_object <- AddModuleScore(final_seurat_object, features = neuroendocrine_cell_scoring_list, 
                                     name = "neuroendocrine cell scoring list", search = TRUE, assay = "RNA")

Idents(final_seurat_object) <- factor(x = Idents(final_seurat_object), 
                                      levels =c("3 - 10-week Whole LPOs","3-week LPOs (NKX2-1-extracted)",
                                                "6-week LPOs (NKX2-1-extracted)","10-week LPOs (NKX2-1-extracted)",
                                                "iBTOs(4-week Sorted)","iBTOs(10-week Sorted)","Human Fetal Bud Tip Organoids","In vivo Bud Tip","In vivo Basal Cell","In vivo Neuroendocrine"))


VlnPlot(object = final_seurat_object, split.by="orig.ident",features = 'bud.tip.cell.scoring.list1') + theme(legend.position="none", axis.title.x = element_blank())
```

